### ISSUE TITLE
Buying with a full inventory will deduct cost but not give the item.

### ISSUE THREAD

**Issue by SydMontague** [chistian95/TradingShops#1]
The plugin never checks whether the buying player actually has enough room for the item they're buying.

Change
https://github.com/chistian95/TradingShops/blob/master/src/es/elzoo/tradingshops/Tienda.java#L302

to
`player.getInventory().addItem(fila.get().getItemOut().clone()).forEach((a, b) -> player.getWorld().dropItem(player.getLocation(), b));	`

to make the plugin drop the items in that case.

**Comment by chistian95** [comment]
Maybe it would be better to just cancel the transaction and send the user a message (?)
Dropping items could be dangerous because someone can steal them

**Comment by SydMontague** [comment]
That's definitely an option as well. I just chose the dropping solution for my server so far, because it's rather easy to implement.

**Comment by chistian95** [comment]
What about a config option to choose wether to drop or cancel the transaction?

**Comment by SydMontague** [comment]
Whatever works for you. :)
