### ISSUE TITLE
NPE while ticking shops

### ISSUE THREAD

**Issue by chistian95** [chistian95/TradingShops#7]
`19.08 14:14:05 [Server] WARN [TradingShops] Task #862 for TradingShops v2.1.1 generated an exception
19.08 14:14:05 [Server] INFO java.lang.NullPointerException: null
19.08 14:14:05 [Server] INFO at java.util.Objects.requireNonNull(Objects.java:203) ~[?:1.8.0_265]
19.08 14:14:05 [Server] INFO at es.elzoo.tradingshops.Shop.tickShops(Shop.java:156) ~[?:?]
19.08 14:14:05 [Server] INFO at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.1.jar:git-Paper-136]
19.08 14:14:05 [Server] INFO at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.1.jar:git-Paper-136]
19.08 14:14:05 [Server] INFO at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1298) ~[patched_1.16.1.jar:git-Paper-136]
19.08 14:14:05 [Server] INFO at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.1.jar:git-Paper-136]
19.08 14:14:05 [Server] INFO at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1213) ~[patched_1.16.1.jar:git-Paper-136]
19.08 14:14:05 [Server] INFO at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1001) ~[patched_1.16.1.jar:git-Paper-136]
19.08 14:14:05 [Server] INFO at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-136]
19.08 14:14:05 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]
19.08 14:14:07 [Server] WARN [TradingShops] Task #862 for TradingShops v2.1.1 generated an exception
19.08 14:14:07 [Server] INFO java.lang.NullPointerException: null
19.08 14:14:07 [Server] INFO at java.util.Objects.requireNonNull(Objects.java:203) ~[?:1.8.0_265]
19.08 14:14:07 [Server] INFO at es.elzoo.tradingshops.Shop.tickShops(Shop.java:156) ~[?:?]
19.08 14:14:07 [Server] INFO at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.1.jar:git-Paper-136]
19.08 14:14:07 [Server] INFO at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.1.jar:git-Paper-136]
19.08 14:14:07 [Server] INFO at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1298) ~[patched_1.16.1.jar:git-Paper-136]
19.08 14:14:07 [Server] INFO at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.1.jar:git-Paper-136]
19.08 14:14:07 [Server] INFO at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1213) ~[patched_1.16.1.jar:git-Paper-136]
19.08 14:14:07 [Server] INFO at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1001) ~[patched_1.16.1.jar:git-Paper-136]
19.08 14:14:07 [Server] INFO at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-136]
19.08 14:14:07 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]
19.08 14:14:09 [Server] WARN [TradingShops] Task #862 for TradingShops v2.1.1 generated an exception
19.08 14:14:09 [Server] INFO java.lang.NullPointerException: null
19.08 14:14:09 [Server] INFO at java.util.Objects.requireNonNull(Objects.java:203) ~[?:1.8.0_265]
19.08 14:14:09 [Server] INFO at es.elzoo.tradingshops.Shop.tickShops(Shop.java:156) ~[?:?]
19.08 14:14:09 [Server] INFO at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.1.jar:git-Paper-136]
19.08 14:14:09 [Server] INFO at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.1.jar:git-Paper-136]
19.08 14:14:09 [Server] INFO at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1298) ~[patched_1.16.1.jar:git-Paper-136]
19.08 14:14:09 [Server] INFO at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.1.jar:git-Paper-136]
19.08 14:14:09 [Server] INFO at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1213) ~[patched_1.16.1.jar:git-Paper-136]
19.08 14:14:09 [Server] INFO at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1001) ~[patched_1.16.1.jar:git-Paper-136]
19.08 14:14:09 [Server] INFO at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-136]
19.08 14:14:09 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]
19.08 14:14:11 [Server] WARN [TradingShops] Task #862 for TradingShops v2.1.1 generated an exception
19.08 14:14:11 [Server] INFO java.lang.NullPointerException: null
19.08 14:14:11 [Server] INFO at java.util.Objects.requireNonNull(Objects.java:203) ~[?:1.8.0_265]
19.08 14:14:11 [Server] INFO at es.elzoo.tradingshops.Shop.tickShops(Shop.java:156) ~[?:?]
19.08 14:14:11 [Server] INFO at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.1.jar:git-Paper-136]
19.08 14:14:11 [Server] INFO at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.1.jar:git-Paper-136]
19.08 14:14:11 [Server] INFO at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1298) ~[patched_1.16.1.jar:git-Paper-136]
19.08 14:14:11 [Server] INFO at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.1.jar:git-Paper-136]
19.08 14:14:11 [Server] INFO at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1213) ~[patched_1.16.1.jar:git-Paper-136]
19.08 14:14:11 [Server] INFO at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1001) ~[patched_1.16.1.jar:git-Paper-136]
19.08 14:14:11 [Server] INFO at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-136]
19.08 14:14:11 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]`

**Comment by Beez0r** [comment]
It is being caused by line 156 in Shop.java:

Objects.requireNonNull(shop1.location.getWorld()).spawnParticle(Particle.VILLAGER_HAPPY, x, y, z, 10, 0.1, 0.1, 0.1);

Can you give any info about the world the shop is in? Is it a custom world or standard (overworld, nether, the_end)?

**Comment by chistian95** [comment]
No idea. It was an issue from another user that reported it back to me. I just put it here to rember myself to fix it.
Seeing the error I think the issue is that this user has a shop in a world that no longer exists

**Comment by Beez0r** [comment]
Yes that is the issue as shop1.location.getWorld() was returning null meaning no world was found
